.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. baghdadbit_qt test_baghdadbit_qt
clean: FORCE
	$(MAKE) -C .. baghdadbit_qt_clean test_baghdadbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_baghdadbit_qt_check
baghdadbit-qt baghdadbit-qt.exe: FORCE
	 $(MAKE) -C .. baghdadbit_qt
